#!/usr/bin/env python
'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
import time

start = time.clock()

fib = [1, 1]
for i in xrange(2, 100):
    n = fib[i-1]+fib[i-2]
    if n>4*10**6:
        break
    fib.append(n)

sum = 0
for i in fib:
    if i%2 == 0:
        sum += i

print fib
print sum
print time.clock()-start
